### ISSUE TITLE
Example fails with "stack smashing detected"

### ISSUE THREAD

**Issue by jgsogo** [jardon-u/wordnet-blast#3]
I'm trying to run the example but it fails with:

```
*** stack smashing detected ***: ./wnb_similarity terminated
Aborted (core dumped)
```

I'm compiling with gcc 4.9.2 in Ubuntu 15.04

**Comment by jardon-u** [comment]
Hi,
Thanks a lot for spotting the problem and contributing to the project.
I am merging your pull request !

**Comment by jgsogo** [comment]
...just to comment: github doesn't have private messages :/

@jardon-u, I am using your library for my master thesis, so I'll probably make some changes/contributions to wordnet-blast. I'll be pleased to know if there is a roadmap or something like that in order to guide the development. I prefer working on top of an existing project than coding my own... 

I plan to implement several distance measures between two concepts (some of them require parsing a corpus), I don't know if this is within the scope of wordnet-blast or not.
